name: example
description: Wiredash example project.
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^2.3.2
  easy_localization_loader: ^0.0.2

  wiredash:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
